[
  "Afghanistan",
  "Albanie",
  "Algérie",
  "Samoa Américaines",
  "Andorre",
  "Angola",
  "Anguilla",
  "Antarctique",
  "Antigua-et-Barbuda",
  "Argentine",
  "Arménie",
  "Aruba",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Bélarus",
  "Belgique",
  "Belize",
  "Bénin",
  "Bermudes",
  "Bhoutan",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunéi Darussalam",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "Îles Caïmans",
  "Centrafricaine, République",
  "Tchad",
  "Chili",
  "Chine",
  "Île Christmas",
  "Îles Cocos (Keeling)",
  "Colombie",
  "Comores",
  "Congo, La République Démocratique du",
  "République du Congo",
  "Îles Cook",
  "Costa Rica",
  "Côte D'ivoire",
  "Croatie",
  "Cuba",
  "Chypre",
  "République Tchèque",
  "Danemark",
  "Djibouti",
  "Dominique",
  "Dominicaine, République",
  "Timor-Leste (Timor Oriental)",
  "Équateur",
  "Égypte",
  "El Salvador",
  "Guinée Équatoriale",
  "Érythrée",
  "Estonie",
  "Éthiopie",
  "Falkland, Îles (Malvinas)",
  "Îles Féroé",
  "Fidji",
  "Finlande",
  "France",
  "Guyane Française",
  "Polynésie Française",
  "Terres Australes Françaises",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Allemagne",
  "Ghana",
  "Gibraltar",
  "Grèce",
  "Groenland",
  "Grenade",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinée",
  "Guinée-Bissau",
  "Guyana",
  "Haïti",
  "Saint-Siège (État de la Cité du Vatican)",
  "Honduras",
  "Hong-Kong",
  "Hongrie",
  "Islande",
  "Inde",
  "Indonésie",
  "République Islamique d' Iran",
  "Iraq",
  "Irlande",
  "Israël",
  "Italie",
  "Côte D'ivoire",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakstan",
  "Kenya",
  "Kiribati",
  "Corée, République Populaire Démocratique de (Corée du Nord)",
  "Corée, République de (Corée du Sud)",
  "Kosovo",
  "Koweït",
  "Kirghizistan",
  "Lao, République Démocratique Populaire",
  "Lettonie",
  "Liban",
  "Lesotho",
  "Libéria",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaisie",
  "Maldives",
  "Mali",
  "Malte",
  "Îles Marshall",
  "Martinique",
  "Mauritanie",
  "Île Maurice",
  "Mayotte",
  "Mexique",
  "États Fédérés de Micronésie",
  "Moldova, République de",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Montserrat",
  "Maroc",
  "Mozambique",
  "Myanmar, Birmanie",
  "Namibie",
  "Nauru",
  "Népal",
  "Pays-Bas",
  "Antilles Néerlandaises",
  "Nouvelle-Calédonie",
  "Nouvelle-Zélande",
  "Nicaragua",
  "Niger",
  "Nigéria",
  "Nioué",
  "Macédoine du Nord",
  "Îles Mariannes du Nord",
  "Norvège",
  "Oman",
  "Pakistan",
  "Palaos",
  "Autorité Nationale Palestinienne",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pérou",
  "Philippines",
  "Pitcairn",
  "Pologne",
  "Portugal",
  "Porto Rico",
  "Qatar",
  "Ile de la Réunion",
  "Roumanie",
  "Russie, Fédération de",
  "Rwanda",
  "Saint-Kitts-et-Nevis",
  "Sainte-Lucie",
  "Saint-Vincent-et-les Grenadines",
  "Samoa",
  "Saint-Marin",
  "Sao Tomé-et-Principe",
  "Arabie Saoudite",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Salomon, Îles",
  "Somalie",
  "Afrique du Sud",
  "Soudan du Sud",
  "Espagne",
  "Sri Lanka",
  "Soudan",
  "Suriname",
  "Swaziland",
  "Suède",
  "Suisse",
  "Syrienne, République Arabe",
  "Taïwan, Province de Chine",
  "Tadjikistan",
  "Tanzanie, République-Unie de",
  "Thaïlande",
  "Tibet",
  "Timor-Leste (Timor Oriental)",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turquie",
  "Turkménistan",
  "Turks et Caïques, Îles",
  "Tuvalu",
  "Ouganda",
  "Ukraine",
  "Émirats Arabes Unis",
  "Royaume-Uni",
  "États-Unis",
  "Uruguay",
  "Ouzbékistan",
  "Vanuatu",
  "Saint-Siège (État de la Cité du Vatican)",
  "Venezuela",
  "Viêt Nam",
  "Îles Vierges Britanniques",
  "Îles Vierges des États-Unis",
  "Wallis et Futuna",
  "Sahara Occidental",
  "Yémen",
  "Zambie",
  "Zimbabwe"
]